default:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: "{{ env_var('GCP_PROJECT') }}"
      dataset: dbt_nkhoa
      threads: 4 # Must be a value of 1 or greater
      keyfile: credential.json
      OPTIONAL_CONFIG: VALUE